baseURL = "https://apoorvasharma7.com/"
languageCode = "en-us"
title = "Apoorva Sharma"

[pagination]
  pagerSize = 10

[params]
  description = "Software Engineer, systems thinking, tech and fitness writing."

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "movement"
    name = "Movement"
    url = "/movement/"
    weight = 2

  [[menu.main]]
    identifier = "tech"
    name = "Tech"
    url = "/tech/"
    weight = 3

  [[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = 4

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 6

[taxonomies]
  category = "categories"
  tag = "tags"
